---
kind: Service
apiVersion: v1
metadata:
  name: postgres-entropy-ejp
spec:
  selector:
    app: postgres-entropy-ejp
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 30400
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment-entropy-ejp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-entropy-ejp
  template:
    metadata:
      labels:
        app: postgres-entropy-ejp
    spec:
      containers:
      - name: postgres
        image: lutando/postgres-entropy #user:lutando; password:lutando
        imagePullPolicy: Always
        ports:
        - name: postgresql
          containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: entropy
      restartPolicy: Always