---
kind: Service
apiVersion: v1
metadata:
  name: postgres-journal-service
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 30700
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-journal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: lutando/postgres-entropy #user:lutando; password:lutando
        imagePullPolicy: Always
        ports:
        - name: postgresql
          containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: entropy
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: postgres-projection-service
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 30701
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-projection-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: lutando/postgres-entropy #user:lutando; password:lutando
        imagePullPolicy: Always
        ports:
        - name: postgresql
          containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: entropy
      restartPolicy: Always