apiVersion: v1
kind: Service
metadata:
  name: laundry-frontend
  labels:
    run: laundry-frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30505
    protocol: TCP
    name: http
  selector:
    run: laundry-frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: laundry-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: laundry-frontend
    spec:
      containers:
      - name: laundry-frontend
        image: lutando/laundry-frontend:latest
        ports:
        - containerPort: 80