kind: Service
apiVersion: v1
metadata:
  name: simpleapi-service
spec:
  selector:
    app: simple-api
  labels:
    project: entropy
    lab: elastick8s-api
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5001
    nodePort: 30600
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapi-deployment
  labels:
    app: simple-api
    project: entropy
    lab: elastick8s-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
        project: entropy
        lab: elastick8s-api
    spec:
      containers:
      - name: simple-api
        image: lutando/simple-api
        ports:
        - containerPort: 5001