kind: Service  
apiVersion: v1  
metadata:  
  name: eventstore
  labels:
    project: entropy
    lab: event-journal-playground
spec:  
  selector:
    app: eventstore
  ports:
    - protocol: TCP
      port: 1112
      targetPort: 1112
      nodePort: 30405
  type: NodePort