kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: eventstore-pv-claim
  labels:
    project: entropy
    lab: event-journal-playground
spec:  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2.5Gi
