---
kind: Service
apiVersion: v1
metadata:
  name: redis-entropy-ejp
  labels:
    project: entropy
    lab: event-journal-playground
spec:
  selector:
    app: redis-entropy-ejp
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    nodePort: 30401
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    project: entropy
    lab: event-journal-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-entropy-ejp
  template:
    metadata:
      labels:
        app: redis-entropy-ejp
    spec:
      containers:
      - name: redis
        image: lutando/redis-entropy #password lutando
        ports:
        - name: redis
          containerPort: 6379
      restartPolicy: Always