
kind: Service
apiVersion: v1
metadata:
  name: nodejs-service
  labels:
    project: entropy
    lab: elastick8s-prototype
spec:
    selector:
      app: nodejs-api
    ports:
      - name: http
        port: 80
        targetPort: 8080
        nodePort: 30100
    type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
    project: entropy
    lab: elastick8s-prototype
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
        project: entropy
        lab: elastick8s-prototype
    spec:
      containers:
      - name: nodejs-hello
        image: lutando/simple-node
        ports:
        - containerPort: 8080